BaseSetting:
    Game_path: F:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
    Model_path: I:\AI\LimbusCompany\LimbusCompanySRA\src\model\LBC.pt
    Pip_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\pip.exe
    Python_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\python.exe
Enkephalin:
    auto_exchange_enkephalin: false
Luxcavation:
    exp_choose:
        '1': 经验采光#1
        '2': 经验采光#2
        '3': 经验采光#3
        '4': 经验采光#4
        '5': 经验采光#5
        '6': 经验采光#6
        '7': 经验采光#7
        selected: 1
    exp_switch: true
    luxcavation_loop_count: '1'
    thread_choose:
        '1': 傲慢
        '2': 嫉妒
        '3': 暴怒
        '4': 色欲
        '5': 怠惰
        '6': 暴食
        '7': 忧郁
        selected: 1
    thread_switch: false
Mirror_Dungeons:
    mirror_loop_count: '1'
    mirror_only_flag: false
    mirror_switch: false
    theme_pack_choose: '[''被遗忘者们'', ''无归属者'', ''身无分文的赌徒'', ''自动工厂'', ''无慈悲者'', ''钉与锤'',
        ''信仰与侵蚀'', ''无作为者'', ''巢，工坊，技术'', ''无改变者'', ''湖的世界'', ''伏行深渊'', ''定义为恶'',
        ''宅邸的副产物'', ''某个世界'', ''地狱鸡'', ''20区的奇迹'', ''肉斩骨断'', ''时间杀人时间'', ''WARP快车谋杀案'',
        ''紫罗兰的正午'', ''斩切者们'', ''当斩之物'', ''穿刺者们'', ''当刺之物'', ''破坏者们'', ''压抑的愤怒'', ''受情感压抑者'',
        ''沉迷的色欲'', ''捆缚的色欲'', ''因情感困惑者'', ''徒劳的怠惰'', ''停滞的怠惰'', ''一声叹息'', ''循环呼吸'',
        ''动力渐盈'', ''电闪雷鸣'', ''沉沦泛滥'', ''沉于苦痛'', ''破竹之势'']'
