BaseSetting:
    Game_path: F:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
    Model_path: I:\AI\LimbusCompany\LimbusCompanySRA\src\model\LBC.plan
    Pip_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\pip.exe
    Python_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\python.exe
    ocr_language:
        '1': config_chinese.txt
        '2': config_en.txt
        '3': config_korean.txt
        '4': config_japan.txt
        selected: 1
    root_path: I:\AI\LimbusCompany\LimbusCompanySRA
Enkephalin:
    auto_exchange_enkephalin: false
Luxcavation:
    exp_choose:
        '1': 经验采光#1
        '2': 经验采光#2
        '3': 经验采光#3
        '4': 经验采光#4
        '5': 经验采光#5
        '6': 经验采光#6
        '7': 经验采光#7
        selected: 4
    exp_switch: false
    luxcavation_loop_count: 2
    thread_choose:
        '1': 傲慢
        '2': 嫉妒
        '3': 暴怒
        '4': 色欲
        '5': 怠惰
        '6': 暴食
        '7': 忧郁
        selected: 1
    thread_switch: false
Mirror_Dungeons:
    ego_gift_choose:
        '1': 烧伤
        '10': 打击
        '2': 流血
        '3': 震颤
        '4': 破裂
        '5': 沉沦
        '6': 呼吸法
        '7': 充能
        '8': 斩击
        '9': 突刺
        selected: 1
    ego_gift_list:
        充能:
        - 员工证
        - 便携式电源插座
        - 夜视镜
        - 简历
        - 护腕
        - 避雷针
        - 充能式手套
        - 物理屏蔽力场
        - 第一类永动机
        - 不间断电源装置
        - 解除限制的除颤仪
        - 巡逻用手电筒
        - 仿造发电机
        - 摩擦残片
        - 微缩电线杆
        - 1B型八角螺栓
        - 绝缘子
        - 第五类永动机
        - E型次元短剑
        - 便携式力场电池
        - 生物发电电池
        - 心脏反应模块
        - 义体关节伺服电机
        - 自动关节
        - 过度充能电池
        - 永动伺服电机
        - 心动力宝石
        - 错位的晶体管
        呼吸法:
        - 烟斗
        - 石冢
        - 四叶草
        - 追忆吊坠
        - 雾化吸入器
        - 明镜止水
        - 内啡肽试剂组
        - 马蹄铁饰物
        - 福袋
        - 魔鬼所享
        - 绿色鞘翅
        - 老旧的木雕人偶
        - 留恋
        - 骄慢残片
        - 某日的记忆
        - 天使所私
        - 追忆
        - 桶装烈酒
        - 捕鲸枪义腿
        - 照亮前方的汽灯
        - 毛球帽
        - 巨大的礼物袋
        - 损坏的刀刃
        - 损坏的竹笠
        打击:
        - 此刻的神色
        - 谷底之星
        - 作祟
        - 加压绷带
        - 时间缰绳
        - 紧握的雕像
        - 破碎的记忆
        - 次元分类回收箱
        - 口袋助记卡
        - 次元知觉变体
        - 复仇账簿
        斩击:
        - 梦中的电子羊
        - 手术用刀
        - 虚饰的和平
        - 裁缝用剪刀
        - 决意
        - 宣判之刻
        - 被剪去的记忆
        - 磨损的砥石
        - 拐杖短剑
        - 云纹鹤颈瓶
        - 破碎的大剑
        - 锈蚀的刀柄
        - 红色流苏
        - 壮观
        - 不动
        - 陈旧的长袍
        沉沦:
        - 赤色指令
        - 荆棘之路
        - 融化的时钟发条
        - 仲冬夜之噩梦
        - 遗骸碎片
        - 美感
        - 无头肖像
        - 破碎罗盘
        - 黑色乐谱
        - 古木陷阱
        - 破布
        - 庄严
        - 彼方之星
        - 蚕食残片
        - 如歌
        - 褪色的外套
        - 碎裂的骨片
        - 浪景球
        - 袭来的波浪
        - 冰封的哀嚎
        - 霜冻足迹
        - 精神污染加速气体
        - 泄露的脑啡肽
        - 安息
        流血:
        - 嗜伤甲虫
        - 染血铁钉
        - 白棉花
        - 又小又可能很坏的玩偶
        - 烟霾与铁丝网
        - 锈蚀的美工刀
        - 红染棉花
        - 锈蚀的笼头
        - 血雾
        - 被扣留的颂歌
        - 纠缠捆束
        - 敬畏
        - 安息之地
        - 魅惑残片
        - 蜜拉卡
        - 撕裂的血袋
        - 虔诚
        - 出血性休克
        - 封装蛆虫
        - 钉与锤之书
        - 污秽
        - 被污染的针与线
        - 破碎的刀刃
        - 孝心
        烧伤:
        - 炼狱炎蝶之梦
        - 尘归尘
        - 炽热的羽毛
        - 单点打击逻辑电路
        - 炎鳞
        - 土归土
        - 烧焦的圆盘
        - 炽热的智慧
        - 镇魂
        - 熔化的石蜡
        - 偏振光
        - 郁火
        - 火光花
        - 业火残片
        - 万年炖锅
        - 万年炉火
        - 烹饪秘诀书
        - 盗来的火焰
        - 火热多汁琵琶腿
        破裂:
        - 成捆的符咒
        - 玫瑰王冠
        - 雷击木
        - 标准负荷电池
        - 荆棘套索
        - 快感
        - 损坏的左轮手枪
        - 荧光灯
        - 恍惚镜
        - 有烟火药
        - 骨桩
        - 破伞
        - 寻死者
        - 欲望残片
        - 终末的碎片
        - 荆棘捕绳
        - 奇怪的石像
        - 破绽
        - 黑檀胸针
        - 未寄出的信
        - 干巴柴涩鸡胸肉
        - 废料蟹脑髓泡酒
        突刺:
        - 黏性淤浆
        - 头骨收藏
        - 木工用长钉
        - 曾经的祝福
        - 撕裂的弹带
        - 磨尖的树枝
        - 破洞的记忆
        - 高弹性钢鞋
        - 证明的羽饰
        - 磨破的衣袖
        - 决斗范本第三卷
        震颤:
        - 绿光果实
        - 融化的眼球
        - 辉光变动仪
        - 震荡手环
        - 暴雨
        - 残响
        - 真理之钟
        - 震颤耦合
        - 生物剧毒药瓶
        - 剧毒外皮
        - 酸味的酒香
        - 镜触觉通感
        - 齿轮发条
        - 惰性残片
        - 宝石振子
        - 摇晃的酒桶
        - 嵌合的齿轮
        - 震中
        - 无振八方钟
        - 油腻的扳手
        - 银色的表壳
        - 褪色的表壳
        - 蚀刻的指针
        - 锈蚀的指针
        - 涓滴之杯
        - 怀表：Type L
        - 怀表：Type E
        - 怀表：Type Y
        - 怀表：Type P
    grace_of_the_dreaming_star_choose:
    - 起始之星
    - 星云的宠爱
    mirror_dungeons_choose:
        '1': 梦中之镜
        '2': 呼啸之镜
        selected: 1
    mirror_loop_count: 1
    mirror_only_flag: true
    mirror_switch: true
    sinner_choose:
    - 李箱
    - 浮士德
    - 以实玛利
    - 鸿璐
    - 良秀
    theme_pack_choose:
    - 被遗忘者们
    - 无归属者
    - 身无分文的赌徒
    - 自动工厂
    - 无慈悲者
    - 钉与锤
    - 落泪者们
    - 地狱鸡
    - 去·海·边
    - 当刺之物
    - 破坏者们
    - 当碎之物
    - 受情感压抑者
    - 沉迷的色欲
    - 因情感困惑者
    - 待情感懒惰者
    - 吞噬的暴食
    - 堕落的忧郁
    - 虚张声势的傲慢
    - 寒微的嫉妒
    - 缭乱的波动
    - 一声叹息
