BaseSetting:
    Game_path: F:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
    Model_path: I:\AI\LimbusCompany\LimbusCompanySRA\src\model\LBC.pt
    Pip_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\pip.exe
    Python_path: F:\.virtualenvs\LimbusCompanySRA\Scripts\python.exe
Enkephalin:
    auto_exchange_enkephalin: false
Luxcavation:
    exp_choose:
        '1': 经验采光#1
        '2': 经验采光#2
        '3': 经验采光#3
        '4': 经验采光#4
        '5': 经验采光#5
        '6': 经验采光#6
        '7': 经验采光#7
        selected: 1
    exp_switch: false
    luxcavation_loop_count: '1'
    thread_choose:
        '1': 傲慢
        '2': 嫉妒
        '3': 暴怒
        '4': 色欲
        '5': 怠惰
        '6': 暴食
        '7': 忧郁
        selected: 1
    thread_switch: false
Mirror_Dungeons:
    mirror_battle_count: 5
    mirror_loop_count: 1
    mirror_only_flag: false
    mirror_switch: true
    theme_pack_choose:
    - 被遗忘者们
    - 无归属者
    - 身无分文的赌徒
    - 自动工厂
    - 无慈悲者
    - 钉与锤
    - 落泪者们
    - 地狱鸡
    - 去·海·边
    - 当刺之物
    - 破坏者们
    - 当碎之物
    - 受情感压抑者
    - 沉迷的色欲
    - 因情感困惑者
    - 待情感懒惰者
    - 吞噬的暴食
    - 堕落的忧郁
    - 虚张声势的傲慢
    - 寒微的嫉妒
    - 缭乱的波动
    - 一声叹息
