name: Labeler Workflow

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

jobs:
  label-pr:
    name: Label Pull Requests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Label PR based on changed files
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml

  label-issue:
    name: Label Issues
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Label Issues by Keywords
      uses: actions/issue-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/issue-labeler.yml
