name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure files are stable
        run: |
          echo "Waiting for file system stability..."
          sleep 5 # Add a brief delay to avoid race conditions

      - name: Prepare workspace
        run: |
          echo "Copying files to a temporary directory..."
          mkdir -p temp_workspace
          rsync -av --exclude=".github" --exclude=".idea" ./ temp_workspace/

      - name: Create ZIP archive
        run: |
          echo "Creating ZIP archive..."
          zip -r temp_workspace/source-code.zip temp_workspace

      - name: Create TAR.GZ archive
        run: |
          echo "Creating TAR.GZ archive..."
          tar --warning=no-file-changed -czvf temp_workspace/source-code.tar.gz -C temp_workspace .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload ZIP Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./temp_workspace/source-code.zip
          asset_name: source-code.zip
          asset_content_type: application/zip

      - name: Upload TAR.GZ Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./temp_workspace/source-code.tar.gz
          asset_name: source-code.tar.gz
          asset_content_type: application/gzip
